import { Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";

// A distinctive "AI layer" card used throughout the app to surface
// natural-language analysis generated by the operational copilot.
export function AICard({
  title = "Inteligência Operacional",
  children,
  action,
  className,
}: {
  title?: string;
  children: React.ReactNode;
  action?: React.ReactNode;
  className?: string;
}) {
  return (
    <div
      className={cn(
        "relative overflow-hidden rounded-xl border border-brand-100 bg-gradient-to-br from-brand-50 via-white to-violet-50 p-5 shadow-card",
        className
      )}
    >
      <div className="pointer-events-none absolute -right-8 -top-8 h-32 w-32 rounded-full bg-brand-200/30 blur-2xl" />
      <div className="relative">
        <div className="mb-3 flex items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-brand-600 text-white shadow-sm">
              <Sparkles className="h-4 w-4" />
            </div>
            <span className="text-sm font-semibold text-slate-900">{title}</span>
            <span className="rounded-full bg-brand-100 px-2 py-0.5 text-[10px] font-medium text-brand-700">
              IA
            </span>
          </div>
          {action}
        </div>
        <div className="text-sm leading-relaxed text-slate-600">{children}</div>
      </div>
    </div>
  );
}
